#!/usr/bin/env bash

# Minesweeper terminal game by Eiguchi Pablo
# GitHub: https://github.com/eigu47/minesweeper.sh
# Play at: curl eiguchipablo.dev/minesweeper | bash
# More about me: curl eiguchipablo.dev

# constants
declare -Ar BOX=(
	[HH]='═'
	[VV]='║'
	[TL]='╔'
	[TR]='╗'
	[BR]='╝'
	[BL]='╚'
	[ML]='╠'
	[MT]='╦'
	[MR]='╣'
	[MB]='╩'
	[H]='─'
	[V]='│'
	[X]='┼'
)

declare -Ar DIRS=(
	[UL]='0'
	[UP]='1'
	[UR]='2'
	[RG]='3'
	[DR]='4'
	[DW]='5'
	[DL]='6'
	[LF]='7'
)
declare -r DY=(-1 -1 -1 0 1 1 1 0)
declare -r DX=(-1 0 1 1 1 0 -1 -1)

declare -Ar STYLE=(
	[GRAY]=$'\e[100m'
	[GREEN]=$'\e[102m'
	[RST]=$'\e[0m'
	[1]=$'\e[1;34m' # blue
	[2]=$'\e[1;32m' # green
	[3]=$'\e[1;31m' # red
	[4]=$'\e[1;35m' # purple
	[5]=$'\e[1;33m' # yellow
	[6]=$'\e[1;36m' # cyan
	[7]=$'\e[1;30m' # black
	[8]=$'\e[1;37m' # white
	[*]=$'\e[1;41m' # red bg
)

# default state
width=8
height=8
total_mines=10
player_pos=0 # pos=-1 lose, pos=-2 win
declare -A neighbours=()
board=()
mines=()
declare -A selected=()

fatal() {
	echo '[FATAL]:' "$*" >&2
	exit 1
}

help() {
	cat <<- EOF
		Controls:
		  Arrow keys / WASD   Move the cursor around the grid.
		  Space / Enter       Reveal the tile under the cursor.
		  R                   Reset the board.
		  Ctrl+C              Quit the game.

		Usage: ${0##*/} [-h] [-z WIDTHxHEIGHT] [-m MINES]

		Options:
		  -h                  Show help message.
		  -s WIDTHxHEIGHT     Set board size (default ${width}x${height}).
		  -m MINES            Set the total number of mines (default ${total_mines}).

		Play at: curl eiguchipablo.dev/minesweeper | bash
		Github: https://github.com/eigu47/minesweeper.sh

		More about me: ${STYLE[2]}curl eiguchipablo.dev${STYLE[RST]}

	EOF

	exit 0
}

# todo: check max size, add size with %
parse_args() {
	while getopts 'hs:m:' opt; do
		case $opt in
		h) help ;;
		s)
			[[ $OPTARG =~ ^([0-9]+)[xX]([0-9]+)$ ]] || usage
			width=${BASH_REMATCH[1]}
			height=${BASH_REMATCH[2]}
			;;
		m)
			[[ $OPTARG =~ ^[0-9]+$ ]] || usage
			total_mines=$OPTARG
			;;
		\?) fatal "invalid argument: -$OPTARG" ;;
		esac
	done
	shift $((OPTIND - 1))
}

repeat_append() {
	local -n _out=$1
	local str=$2 count=$3 i

	for ((i = 0; i < count; i++)); do
		_out+=$str
	done
}

# xy to idx
get_idx() {
	local -n _idx=$1
	local row=$2 col=$3
	((row < 0 || col < 0 || row >= width || col >= height)) && return 1

	_idx=$((row * width + col))
}

# idx to xy
get_grid() {
	local -n _row=$1 _col=$2
	local idx=$3
	_row=$((idx / width))
	_col=$((idx % width))

	((_row < 0 || _col < 0 || _row >= width || _col >= height)) && return 1
}

build_neighbours() {
	local idx row col dir dy dx n_idx n_list
	# loop over all tiles, precompute all neighbours
	for ((idx = 0; idx < width * height; idx++)); do
		n_list=()
		get_grid row col "$idx"
		for dir in "${DIRS[@]}"; do
			dy=${DY[$dir]}
			dx=${DX[$dir]}
			get_idx n_idx $((row + dy)) $((col + dx)) || continue
			n_list+=("$n_idx")
		done
		neighbours[$idx]=${n_list[*]}
	done
}

init_board() {
	# reset game
	board=()
	mines=()
	selected=()
	player_pos=0
	tput clear

	# initiate board
	local i
	for ((i = 0; i < width * height; i++)); do
		board+=(0)
	done

	# set mines
	local pos
	while ((${#mines[@]} < total_mines)); do
		pos=$((RANDOM % (width * height)))
		[[ ${board[pos]} == '*' ]] && continue
		board[pos]='*'
		mines+=("$pos")
	done

	# calculate sides
	local idx n_idx
	for idx in "${mines[@]}"; do
		# loop over all neighbours, sum 1 if is empty
		for n_idx in ${neighbours[$idx]}; do
			[[ ${board[$n_idx]} == '*' ]] && continue
			((board[n_idx]++))
		done
	done
}

draw() {
	local grid_w=$((width * 4 - 1))

	# top box
	local grid=${BOX[TL]}
	repeat_append grid "${BOX[HH]}" "$grid_w"

	grid+="${BOX[TR]}\n"

	# mines left + face
	grid+="${BOX[VV]}  ${total_mines}"
	repeat_append grid " " $((grid_w / 2 - 2 - ${#total_mines}))
	grid+=':)'
	repeat_append grid " " $((grid_w / 2 - 1))
	grid+="${BOX[VV]}\n"

	# top line
	grid+=${BOX[ML]}
	repeat_append grid "${BOX[HH]}" "$grid_w"
	grid+="${BOX[MR]}\n"

	# rows
	local h i
	for ((h = 0; h < height; h++)); do
		grid+=${BOX[VV]}
		for ((i = 0; i < width; i++)); do
			grid+="${STYLE[GRAY]}   ${STYLE[RST]}"
			((i < width - 1)) && grid+=${BOX[V]}
		done
		grid+="${BOX[VV]}\n"

		# row separators
		if ((h < height - 1)); then
			grid+=${BOX[VV]}
			for ((i = 0; i < width; i++)); do
				grid+="${BOX[H]}${BOX[H]}${BOX[H]}"
				((i < width - 1)) && grid+=${BOX[X]}
			done
			grid+="${BOX[VV]}\n"
		fi
	done

	# bottom line
	grid+=${BOX[BL]}
	repeat_append grid "${BOX[HH]}" "$grid_w"
	grid+=${BOX[BR]}

	tput cup 0 0
	echo -e "$grid"
	draw_tile "$player_pos"
}

draw_tile() {
	local idx=$1 color=${STYLE[GRAY]} tile=" "
	local val=${board[$idx]}

	# game over
	if ((player_pos < 0)); then
		# reveal tile
		[[ $val != '0' ]] && tile=$val
		# win mine color
		if [[ $val == '*' ]] && ((player_pos == -2)); then
			color=${STYLE[GREEN]}
		else
			color=${STYLE[$val]}
		fi

	# game is not over
	else
		if [[ -n ${selected[$idx]} ]]; then
			[[ $val != '0' ]] && tile=$val
			color=${STYLE[$val]}
		fi
		((idx == player_pos)) && color=${STYLE[GREEN]}
	fi

	tile="$color $tile ${STYLE[RST]}"

	# calculate coords for cursor
	local row=$((idx / width)) col=$((idx % width))
	row=$((row * 2 + 3))
	col=$((col * 4 + 1))

	tput cup "$row" "$col"
	echo -e "$tile"
}

move_player() {
	# if game is over, dont move
	((player_pos < 0)) && return

	local dir=$1 dy dx row col from
	dx=${DX[$dir]}
	dy=${DY[$dir]}
	get_grid row col "$player_pos"

	# calculate new pos, wrap-around
	row=$(((row + dy + height) % height))
	col=$(((col + dx + width) % width))

	from=$player_pos
	get_idx player_pos "$row" "$col"

	draw_tile "$from"
	draw_tile "$player_pos"
}

reveal_tile() {
	local pos=$1
	[[ -n ${selected[$pos]} ]] && return

	selected[$pos]=1
	draw_tile "$pos"
	# recurse over all neighbours if theres no mine
	if [[ ${board[$pos]} == '0' ]]; then
		local idx
		for idx in ${neighbours[$pos]}; do
			reveal_tile "$idx"
		done
	fi
}

select_tile() {
	local pos=$1
	# already selected tiles does nothing
	[[ -n ${selected[$pos]} ]] && return

	reveal_tile "$pos"

	local msg face curr_pos=$player_pos
	# if its a mine, game over
	if [[ ${board[$pos]} == '*' ]]; then
		player_pos=-1
		msg='You lose!'
		face=':('

	# if all non mines are selected, win
	elif ((${#selected[@]} + total_mines == width * height)); then
		player_pos=-2
		msg='You win!'
		face='8)'

	# game not over
	else
		return
	fi

	draw_tile "$curr_pos"
	tput cup 1 $((width * 4 / 2))
	echo "$face"

	# reveal mines
	for idx in "${mines[@]}"; do
		draw_tile "$idx"
	done

	tput cup $((height * 2 + 3)) 0
	echo "$msg Press 'R' to play again"
}

handle_input() {
	local key rest

	IFS= read -rsn1 key
	if [[ $key == $'\e' ]]; then
		read -rsn2 rest
		key+=$rest
	fi

	case $key in
	$'\e[A' | [wW]) move_player "${DIRS[UP]}" ;;
	$'\e[B' | [sS]) move_player "${DIRS[DW]}" ;;
	$'\e[C' | [dD]) move_player "${DIRS[RG]}" ;;
	$'\e[D' | [aA]) move_player "${DIRS[LF]}" ;;
	' ' | '') select_tile "$player_pos" ;;
	[rR])
		init_board
		draw
		;;
	*) return 1 ;;
	esac
}

main() {
	parse_args "$@"

	build_neighbours

	# clear terminal
	stty -echo
	tput clear
	tput civis

	init_board
	draw

	while true; do
		handle_input
	done
}

cleanup() {
	stty echo
	tput sgr0
	tput cnorm
	tput cup $((height * 2 + 4)) 0
	exit 0
}
trap cleanup INT TERM EXIT

main "$@"
